version: "3.8"

services:
  app:
    build: .
    image: parking-slot-app
    container_name: parking-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/parking_db
      SPRING_DATASOURCE_USERNAME: parking_user
      SPRING_DATASOURCE_PASSWORD: parking_pass

  mysql:
    image: mysql:8.0
    container_name: parking-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parking_db
      MYSQL_USER: parking_user
      MYSQL_PASSWORD: parking_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
